module.exports = {
  testEnvironment: 'node',
  testTimeout: 60000,
  maxWorkers: 1,
  coverageDirectory: 'coverage',
  collectCoverageFrom: [
    'app.js',
    'db.js',
    'jwt.js',
    'config/**/*.js',
    'controllers/apiController.js',
    'controllers/customerController.js',
    'controllers/dashController.js',
    'controllers/expenseController.js',
    'controllers/inventoryController.js',
    'controllers/supplierController.js',
    'middleware/authMiddleware.js',
    'utils/pagination.js',
    'models/**/*.js',
    'routes/**/*.js',
    'public/assets/js/form-utils.js',
    'utils/audit.js',
    'utils/reportUtils.js',
    'utils/validate.js',
    '!**/node_modules/**'
  ],
  coverageReporters: ['lcov', 'text', 'clover'],
  testMatch: ['**/tests/**/*.test.js'],
  testResultsProcessor: 'jest-sonar-reporter'
};
