const PDFDocument = require('pdfkit');

// Brand palette taken from the app's own UI (public/assets/css/style.css)
// so exported reports look like an extension of the product rather than a
// bare data dump.
const BRAND = {
  accent: '#ff9f43',
  dark: '#2c2c2c',
  headerText: '#ffffff',
  rowAlt: '#fff5eb',
  rowBorder: '#eeeeee',
  muted: '#8a8a8a'
};

const MARGIN = 30;

function drawHeader(doc, title, subtitle) {
  const bandHeight = 62;
  doc.rect(0, 0, doc.page.width, bandHeight).fill(BRAND.accent);

  doc.fillColor(BRAND.headerText).font('Helvetica-Bold').fontSize(18)
    .text(title, MARGIN, 18, { width: doc.page.width - MARGIN * 2 });

  if (subtitle) {
    doc.font('Helvetica').fontSize(9)
      .text(subtitle, MARGIN, 40, { width: doc.page.width - MARGIN * 2 });
  }

  doc.fillColor(BRAND.dark);
  return bandHeight + 20;
}

function drawFooter(doc, pageNumber) {
  const y = doc.page.height - 30;
  doc.font('Helvetica').fontSize(8).fillColor(BRAND.muted)
    .text('Generated by RMS - Restaurant Management System', MARGIN, y, { width: doc.page.width - MARGIN * 2 - 60, align: 'left' })
    .text('Page ' + pageNumber, doc.page.width - MARGIN - 60, y, { width: 60, align: 'right' });
  doc.fillColor(BRAND.dark);
}

/**
 * Builds a branded PDF report: colored header band, subtitle with the
 * restaurant name and generation date, a styled table (header row, zebra
 * striping, row separators) instead of plain text dumped column by column,
 * and a footer with page numbers.
 */
function generatePdf(title, rows, columns, options = {}) {
  const doc = new PDFDocument({ margin: MARGIN, size: 'A4', bufferPages: true });

  const generatedAt = new Date().toLocaleString();
  const subtitle = [options.restaurantName, 'Generated on ' + generatedAt].filter(Boolean).join('  •  ');

  let y = drawHeader(doc, title, subtitle);

  const tableLeft = MARGIN;
  const tableWidth = doc.page.width - MARGIN * 2;
  const colWidth = tableWidth / columns.length;
  const rowPadding = 6;

  function drawTableHeader() {
    doc.rect(tableLeft, y, tableWidth, 22).fill(BRAND.accent);
    doc.fillColor(BRAND.headerText).font('Helvetica-Bold').fontSize(9);
    columns.forEach((c, i) => {
      doc.text(c.label, tableLeft + i * colWidth + rowPadding, y + 6, { width: colWidth - rowPadding * 2, align: 'left' });
    });
    doc.fillColor(BRAND.dark);
    y += 22;
  }

  drawTableHeader();

  doc.font('Helvetica').fontSize(9);

  if (!rows || rows.length === 0) {
    doc.fillColor(BRAND.muted).font('Helvetica-Oblique')
      .text('No data available for this report.', tableLeft, y + 10, { width: tableWidth, align: 'center' });
    doc.fillColor(BRAND.dark);
  }

  (rows || []).forEach((row, rowIndex) => {
    let maxH = 0;
    const cells = columns.map((c) => {
      const val = c.getValue(row);
      const text = val == null ? '' : String(val);
      const h = doc.heightOfString(text, { width: colWidth - rowPadding * 2 });
      if (h > maxH) maxH = h;
      return text;
    });
    const rowHeight = Math.max(20, maxH + rowPadding * 2);

    if (y + rowHeight > doc.page.height - 45) {
      doc.addPage();
      y = MARGIN;
      drawTableHeader();
      doc.font('Helvetica').fontSize(9);
    }

    if (rowIndex % 2 === 1) {
      doc.rect(tableLeft, y, tableWidth, rowHeight).fill(BRAND.rowAlt);
      doc.fillColor(BRAND.dark);
    }

    cells.forEach((text, i) => {
      doc.text(text, tableLeft + i * colWidth + rowPadding, y + rowPadding, { width: colWidth - rowPadding * 2, align: 'left' });
    });

    doc.moveTo(tableLeft, y + rowHeight).lineTo(tableLeft + tableWidth, y + rowHeight)
      .strokeColor(BRAND.rowBorder).lineWidth(0.5).stroke();

    y += rowHeight;
  });

  const pageRange = doc.bufferedPageRange();
  for (let i = 0; i < pageRange.count; i++) {
    doc.switchToPage(i);
    drawFooter(doc, i + 1);
  }

  doc.end();
  return doc;
}

module.exports = { generatePdf };
